<a href="https://colab.research.google.com/github/pb0383303-prog/ML_LAB_2026-27/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**

NumPy is a Python library created in 2005 that performs numerical calculations. It is generally used for working with arrays.

NumPy also includes a wide range of mathematical functions, such as linear algebra, Fourier transforms, and random number generation, which can be applied to array

**Why Use Numpy**

In Python, we use lists to work with arrays. But when it comes to large array operations, Python lists are not optimized enough.

Numpy arrays are optimized for complex mathematical and statistical operations. Operations on NumPy are up to 50x faster than iterating over native Python lists using loops.

**Import NumPy in Python**

In [3]:
import numpy as np

NumPy Array Creation

In [4]:
# create a list named list1
list1 = [2, 4, 6, 8]

# create numpy array using list1
array1 = np.array(list1)

print(array1)

[2 4 6 8]


Instead of creating a list and using the list variable with the np.array() function, we can directly pass list elements as an argument.

In [5]:
# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)


[2 4 6 8]



**Create a 2-D NumPy Array**

In [6]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

print(array1)

[[1 2 3 4]
 [5 6 7 8]]



**Create a 3-D NumPy Array**

In [7]:

# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


**Check Data Type of a NumPy Array**

In [8]:
# create an array of integers
array1 = np.array([2, 4, 6])

# check the data type of array1
print(array1.dtype)

int64


**Check dimensions of an Numpy Array**

In [9]:
print(array1.ndim)

1


**Check Size of Numpy array**

In [10]:
print(array1.size)

3


**NumPy Array shape Attribute**

In NumPy, the shape attribute returns a tuple of integers that gives the size of the array in each dimension.

In [11]:
array1 = np.array([[1, 2, 3],
                [6, 7, 8]])

# return a tuple that gives size of array in each dimension
print(array1.shape)


(2, 3)


**NumPy Array itemsize Attribute**
In NumPy, the itemsize attribute determines size (in bytes) of each element in the array.

In [12]:
# create a default 1-D array of integers
array1 = np.array([6, 7, 8, 10, 13])

# create a 1-D array of 32-bit integers
array2 = np.array([6, 7, 8, 10, 13], dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)
print(array2.itemsize)

8
4


**NumPy Array data Attribute**

In NumPy, we can get a buffer containing actual elements of the array in memory using the data attribute.

In simpler terms, the data attribute is like a pointer to the memory location where the array's data is stored in the computer's memory.

In [13]:
array1 = np.array([6, 7, 8])
array2 = np.array([[1, 2, 3],
                   	    [6, 7, 8]])

# print memory address of array1's and array2's data
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)




Data of array1 is:  <memory at 0x7e0ce978e440>
Data of array2 is:  <memory at 0x7e0ce96839f0>


**Access Array Elements Using Index**

In [14]:
array1 = np.array([1, 3, 5, 7, 9])

# access numpy elements using index
print(array1[0])
print(array1[2])
print(array1[4])


1
5
9


**Modify Array Elements Using Index**

In [15]:
array1[1]=10
print(array1)

[ 1 10  5  7  9]



**2-D NumPy Array Indexing**

In [16]:
# create a 2D array
array1 = np.array([[1, 3, 5, 7],
                       [9, 11, 13, 15],
                       [2, 4, 6, 8]])


# access the element at the second row and fourth column
element1 = array1[1, 3]  # returns 15
print("4th Element at 2nd Row:",element1)

# access the element at the first row and second column
element2 = array1[0, 1]  # returns 3
print("2nd Element at First Row:",element2)


4th Element at 2nd Row: 15
2nd Element at First Row: 3


**NumPy Statistical Functions**

Functions

median() return the median of an array

mean() return the mean of an array

std() return the standard deviation of an array

percentile() return the nth percentile of elements in an array

min() return the minimum element of an array

max() return the maximum element of an array

In [17]:
# create a 1D array with 5 elements
array1 = np.array([1, 2, 3, 4, 5])

# calculate the median
median = np.median(array1)

print(median)

3.0



**Compute Mean Using NumPy**

In [18]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the mean of marks
mean_marks = np.mean(marks)

print(mean_marks)

77.2


**Standard Deviation of NumPy Array**

In [19]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.std(marks)
print(std_marks)

6.368673331236263


**Numpy Percentile**

In [20]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.percentile(marks,50)
print(std_marks)


78.0


**Numpy min**

In [21]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.min(marks)
print(std_marks)

66


**Numpy max**

In [22]:
# create a numpy array
marks = np.array([76, 78, 81, 66, 85])

# compute the standard deviation of marks
std_marks = np.max(marks)
print(std_marks)


85


**check data type of a numpy 2D Array**

In [23]:
array2=np.array([[1,2,3,4],[5,6,7,8]])
print(array2.dtype)

int64


**check dimensions of numpy 2D Array**

In [24]:
print(array2.ndim)

2


check size of numpy 2D Array

In [25]:
print(array2.size)

8


NumPy 2D Array itemsize Attribute

In [29]:
# create a default 2-D array of integers
array1 = np.array([[6, 7, 8, 10, 13],[2,3,4,5,6]])

# create a 1-D array of 32-bit integers
array2 = np.array(([[6, 7, 8, 10, 13],[2,3,4,5,6]]), dtype=np.int32)

# use of itemsize to determine size of each array element of array1 and array2
print(array1.itemsize)
print(array2.itemsize)


8
4


**Access 2D Array Elements Using Index**

In [31]:
array1 = np.array([[1, 3, 5, 7, 9],[2,4,6,8,10]])

# access numpy elements using index
print(array1[0,1])
print(array1[1,2])
print(array1[1,4])


3
6
10


**Modify 2DArray Elements Using Index**

In [44]:
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])
array1[1,2]=10
print(array1)

[[ 1  2  3  4]
 [ 5  6 10  8]]


**Numpy Stastical Functions**

**median of 2D Array**

In [45]:
median=np.median(array1)
print(median)

4.5


mean of 2D Array

In [46]:
mean=np.mean(array1)
print(mean)

4.875


**standard deviation of 2D Array**

In [47]:
std_marks = np.std(array1)
print(std_marks)


2.8476964374736293


**Numpy Percentile**

In [50]:
std_marks = np.percentile(array1,50)
print(std_marks)

4.5


**Numpy min**

In [51]:
min=np.min(array1)
print(min)

1


**Numpy max**

In [52]:
max=np.max(array1)
print(max)

10


Create a 3-D NumPy Array

In [53]:
array3 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

print(array3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [54]:
print(array3.dtype)

int64


In [55]:
print(array3.ndim)

3


In [56]:
print(array3.size)

24


In [57]:
print(array3.shape)

(2, 3, 4)


In [58]:
print(array3.itemsize)

8


In [59]:
print(array3.data)

In [60]:
print(array3[0,1,2])

7


In [62]:
array3[0,1,2]=10
print(array3)

[[[ 1  2  3  4]
  [ 5  6 10  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [63]:
median=np.median(array3)
print(median)

12.5


In [64]:
mean=np.mean(array3)
print(mean)

12.625


In [65]:
std=np.std(array3)
print(std)

6.848433519182811


In [66]:
percentile=np.percentile(array3,100)
print(percentile)

24.0


In [67]:
min=np.min(array3)
print(min)

1


In [68]:
max=np.max(array3)
print(max)

24
